version: "3.8"
services:
    translation-server:
        build: ./server
        environment:
            ENV: production
            FLASK_APP: /code/server.py
            FLASK_ENV: production
        ports:
            - 5000:5000
    client:
        build: ./client
        ports:
            - 5001:8080
        depends_on: 
            - translation-server
        links: 
            - translation-server